// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDchydKWM7JigfibZWltqWiMrDEyuGUMAE',
    appId: '1:1017424215687:web:a86347e01609e81755c222',
    messagingSenderId: '1017424215687',
    projectId: 'education-app-74250',
    authDomain: 'education-app-74250.firebaseapp.com',
    storageBucket: 'education-app-74250.firebasestorage.app',
    measurementId: 'G-3Q3394Z23J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz9s3d2RDQOYsUgP4f99X5YHFYYaJunzo',
    appId: '1:1017424215687:android:1a8908b4a5b3b36855c222',
    messagingSenderId: '1017424215687',
    projectId: 'education-app-74250',
    storageBucket: 'education-app-74250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7376M89afjtCbXheS3xH6mVSwFu8uiNg',
    appId: '1:1017424215687:ios:dafccb1d431d25d255c222',
    messagingSenderId: '1017424215687',
    projectId: 'education-app-74250',
    storageBucket: 'education-app-74250.firebasestorage.app',
    iosBundleId: 'com.learning.mayiliragu.mayiliragu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDchydKWM7JigfibZWltqWiMrDEyuGUMAE',
    appId: '1:1017424215687:web:531dcd38edfa30c155c222',
    messagingSenderId: '1017424215687',
    projectId: 'education-app-74250',
    authDomain: 'education-app-74250.firebaseapp.com',
    storageBucket: 'education-app-74250.firebasestorage.app',
    measurementId: 'G-0ZZHYGX7F5',
  );
}
